"use client";

import { motion } from "framer-motion";
import { Globe, Zap, CheckCircle2, ChevronRight, Award, Sparkles } from "lucide-react";
import { passport } from "@/data/passport";
import { user } from "@/data/user";
import type { PassportScore } from "@/types";

function ScoreRing({ score, color, size = 80 }: { score: number; color: string; size?: number }) {
  const radius = (size - 10) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;
  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        <circle cx={size / 2} cy={size / 2} r={radius} fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth={6} />
        <motion.circle cx={size / 2} cy={size / 2} r={radius} fill="none" stroke={color} strokeWidth={6}
          strokeLinecap="round" strokeDasharray={circumference}
          initial={{ strokeDashoffset: circumference }}
          animate={{ strokeDashoffset: offset }}
          transition={{ duration: 1.8, ease: "easeOut" }}
          style={{ filter: `drop-shadow(0 0 8px ${color}60)` }} />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-white font-black tabular-nums" style={{ fontSize: size * 0.22 }}>{score}</span>
      </div>
    </div>
  );
}

function SkillBadge({ name, level }: { name: string; level: string }) {
  const levelPct: Record<string, number> = { beginner: 25, intermediate: 55, advanced: 80, expert: 98 };
  const levelColor: Record<string, string> = {
    beginner: "#22C55E", intermediate: "#F59E0B", advanced: "#2563EB", expert: "#7C3AED",
  };
  const pct = levelPct[level] || 50;
  const color = levelColor[level] || "#94A3B8";

  return (
    <div className="p-3 rounded-xl" style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)" }}>
      <div className="flex items-center justify-between mb-2">
        <p className="text-white text-xs font-medium">{name}</p>
        <span className="text-xs capitalize" style={{ color }}>{level}</span>
      </div>
      <div className="h-1 bg-white/5 rounded-full overflow-hidden">
        <motion.div className="h-full rounded-full" style={{ background: color }}
          initial={{ width: 0 }} animate={{ width: `${pct}%` }}
          transition={{ duration: 1, ease: "easeOut" }} />
      </div>
    </div>
  );
}

export default function PassportPage() {
  return (
    <div className="min-h-screen p-8">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <h1 className="text-3xl font-black text-white mb-1">Opportunity Passport</h1>
        <p className="text-zinc-400 text-sm">Your digital career identity — generated by AI</p>
      </motion.div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {/* Left: Passport Card */}
        <div className="xl:col-span-1 space-y-6">
          {/* The Passport */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            whileHover={{ scale: 1.02 }}
            className="relative overflow-hidden rounded-3xl p-7"
            style={{
              background: "linear-gradient(135deg, #0F172A 0%, #1E1B4B 50%, #0F172A 100%)",
              boxShadow: "0 25px 80px rgba(37,99,235,0.3), 0 0 120px rgba(124,58,237,0.15)",
              border: "1px solid rgba(255,255,255,0.08)",
              minHeight: 280,
            }}
          >
            {/* Shimmer */}
            <motion.div className="absolute inset-0"
              animate={{ x: ["-100%", "200%"] }}
              transition={{ duration: 3, repeat: Infinity, repeatDelay: 3 }}
              style={{ background: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.04) 50%, transparent 100%)" }} />

            {/* Country strip */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center text-white text-xs font-black"
                  style={{ background: "linear-gradient(135deg, #2563EB, #7C3AED)" }}>OP</div>
                <div>
                  <p className="text-zinc-500 text-xs font-mono">OPPORTUNITY PASSPORT</p>
                  <p className="text-zinc-600 text-xs font-mono">INDIA → SINGAPORE</p>
                </div>
              </div>
              <Globe className="w-6 h-6 text-zinc-700" />
            </div>

            {/* Avatar + Name */}
            <div className="flex items-center gap-4 mb-6">
              <div className="w-16 h-16 rounded-2xl flex items-center justify-center text-white font-black text-xl"
                style={{ background: "linear-gradient(135deg, #2563EB, #7C3AED)" }}>
                {user.avatar}
              </div>
              <div>
                <p className="text-white font-black text-lg">{user.name}</p>
                <p className="text-zinc-400 text-xs">{user.degree}</p>
                <p className="text-zinc-500 text-xs">{user.university}</p>
              </div>
            </div>

            {/* Score */}
            <div className="flex items-center justify-between">
              <div>
                <p className="text-zinc-500 text-xs font-mono mb-1">PASSPORT SCORE</p>
                <div className="flex items-end gap-2">
                  <span className="text-5xl font-black"
                    style={{ background: "linear-gradient(135deg, #2563EB, #7C3AED)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
                    {passport.overallScore}
                  </span>
                  <span className="text-zinc-600 text-xl mb-1">/100</span>
                </div>
              </div>
              <div className="text-right">
                <p className="text-zinc-500 text-xs font-mono mb-1">STATUS</p>
                <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl"
                  style={{ background: "rgba(34,197,94,0.1)", border: "1px solid rgba(34,197,94,0.25)" }}>
                  <div className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                  <span className="text-green-400 text-xs font-bold">ACTIVE</span>
                </div>
              </div>
            </div>

            {/* Score bar */}
            <div className="mt-4 h-1 bg-white/5 rounded-full overflow-hidden">
              <motion.div className="h-full rounded-full"
                style={{ background: "linear-gradient(90deg, #2563EB, #7C3AED)" }}
                initial={{ width: 0 }} animate={{ width: `${passport.overallScore}%` }}
                transition={{ duration: 1.5, delay: 0.5 }} />
            </div>

            {/* Generated at */}
            <p className="text-zinc-600 text-xs font-mono mt-3">
              ISSUED: {new Date(passport.generatedAt).toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" })}
            </p>
          </motion.div>

          {/* Achievements */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-5">
            <div className="flex items-center gap-2 mb-4">
              <Award className="w-4 h-4 text-yellow-400" />
              <h3 className="text-white font-semibold text-sm">Achievements</h3>
            </div>
            <div className="grid grid-cols-2 gap-3">
              {passport.achievements.map((ach) => (
                <div key={ach.id} className="p-3 rounded-xl text-center"
                  style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)" }}>
                  <div className="text-2xl mb-1">{ach.icon}</div>
                  <p className="text-white text-xs font-semibold">{ach.title}</p>
                  <p className="text-zinc-500 text-xs mt-0.5 leading-relaxed">{ach.description}</p>
                </div>
              ))}
            </div>
          </motion.div>
        </div>

        {/* Right: Scores + Skills */}
        <div className="xl:col-span-2 space-y-6">
          {/* AI Summary */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="glass-card p-6" style={{ borderColor: "rgba(37,99,235,0.2)" }}>
            <div className="flex items-center gap-2 mb-3">
              <Sparkles className="w-4 h-4 text-primary" />
              <p className="text-white font-semibold text-sm">AI Summary</p>
            </div>
            <p className="text-zinc-300 text-sm leading-relaxed">{passport.aiSummary}</p>
          </motion.div>

          {/* Score grid */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6">
            <h3 className="text-white font-semibold text-sm mb-5">Passport Scores</h3>
            <div className="grid grid-cols-3 gap-6">
              {passport.scores.map((score) => (
                <div key={score.category} className="text-center">
                  <ScoreRing score={score.score} color={score.color} size={72} />
                  <p className="text-white text-xs font-semibold mt-2">{score.label}</p>
                  <p className="text-zinc-500 text-xs mt-0.5">{score.score}/100</p>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Skills */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6">
            <h3 className="text-white font-semibold text-sm mb-4">Skills Profile</h3>
            <div className="grid grid-cols-2 gap-3">
              {user.skills.map((skill) => (
                <SkillBadge key={skill.name} name={skill.name} level={skill.level} />
              ))}
            </div>
          </motion.div>

          {/* Strengths & Gaps */}
          <div className="grid grid-cols-2 gap-4">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-5">
              <h3 className="text-green-400 font-semibold text-xs uppercase tracking-wide mb-3">Strengths</h3>
              <div className="space-y-2">
                {passport.strengths.map((s) => (
                  <div key={s} className="flex items-start gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-green-400 flex-shrink-0 mt-0.5" />
                    <p className="text-zinc-300 text-xs">{s}</p>
                  </div>
                ))}
              </div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.45 }} className="glass-card p-5">
              <h3 className="text-yellow-400 font-semibold text-xs uppercase tracking-wide mb-3">Gaps to Close</h3>
              <div className="space-y-2">
                {passport.gaps.map((g) => (
                  <div key={g} className="flex items-start gap-2">
                    <ChevronRight className="w-3.5 h-3.5 text-yellow-400 flex-shrink-0 mt-0.5" />
                    <p className="text-zinc-300 text-xs">{g}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
